### ISSUE TITLE
Provide the icons as SVG / Display as SVG

### ISSUE THREAD

**Issue by porglezomp** [aldeka/rustacean.net#2]
I wanted to use the icons today and noticed that they were only available as PNG and Illustrator files. It seems like it would be good to provide it as SVGs as well. I can make a PR if you think this would be good. Questions:

• Should the icons on the page also be SVG with PNG fallback, to save bandwidth?
• How should the downloads be listed? I'm thinking something like replacing the current "Illustrator source file [.ai]" with "[.png] [.ai] [.svg]" as separate download links.

**Comment by aldeka** [comment]
All of that sounds good to me, PR away!

Also feel free to convert only a subset of the Ferris versions if that's easier.

**Comment by porglezomp** [comment]
Additionally, should I update the link when clicking on the image to take you to the SVG, or should it still go to the PNG?

**Comment by aldeka** [comment]
Yeah, link it to the format being shown. The PNG link can go below with the other format(s).
