### ISSUE TITLE
http://www.rustacean.net/ broken

### ISSUE THREAD

**Issue by richelbilderbeek** [aldeka/rustacean.net#26]
Dear maintainer of `http://www.rustacean.net/`,

The webpage `http://www.rustacean.net/` seems not to be deployed anymore.

Cheers, Richel

**Comment by Turbo87** [comment]
@aldeka do you need help with this in any way?

**Comment by aldeka** [comment]
Just deposited more money in the account; the site should load for y'all now!

**Comment by Turbo87** [comment]
awesome, thank you! ❤️
