### ISSUE TITLE
Enable and enforce HTTPS on the website

### ISSUE THREAD

**Issue by pietroalbini** [aldeka/rustacean.net#9]
Hi! I'm Pietro from the Rust infrastructure team!

In a recent audit of the links in the rust-lang.org website we noticed that  rustacean.net is not served with HTTPS. While it's rustacean.net is not an highly critical website, we'd love for all the links on the main Rust website to point to secure resources.

Could you enable HTTPS and add a redirect for insecure connections?  
Thanks!

**Comment by aldeka** [comment]
Done! :) https://rustacean.net/

**Comment by pietroalbini** [comment]
Thanks!
